src/main/java/com/mycompany/jv30_project_final02/entities/OrdersEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv30_project_final02.entities;

import com.mycompany.jv30_project_final02.enums.StatusOrder;
import java.io.Serializable;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author Hi_XV
 */
@Entity
@Table(name = "Orders")
public class OrdersEntity implements Serializable, Comparable<OrdersEntity>{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @Column(name = "orderDate")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd-MM-yyyy")
    private Date orderDate = new Date();
    
    private double totalPrice;
    
    @Enumerated(EnumType.STRING)
    private StatusOrder status = StatusOrder.Ordered; 
    
    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<OrderDetailEntity> orderDetails;
    
    @ManyToOne 
    @JoinColumn(name ="customer_id")
    private CustomerEntity customer;
    
    public OrdersEntity() {
    }

    public List<OrderDetailEntity> getOrderDetails() {
        return orderDetails;
    }

    public void setOrderDetails(List<OrderDetailEntity> orderDetails) {
        this.orderDetails = orderDetails;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
   
    public double getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public StatusOrder getStatus() {
        return status;
    }

    public void setStatus(StatusOrder status) {
        this.status = status;
    }

    public CustomerEntity getCustomer() {
        return customer;
    }

    public void setCustomer(CustomerEntity customer) {
        this.customer = customer;
    }
    
    public String getTotalPriceFormatted(){
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        String priceFormatted = currency.format(totalPrice);
        return priceFormatted;
    }
    
    public String getOrderDateFormatted(){
            SimpleDateFormat dt1 = new SimpleDateFormat("dd-MM-yyyy");
        return dt1.format(orderDate);
    }
    public String totalPriceOrder(){
        double totalPriceOrder = 0;
        for (OrderDetailEntity orderDetail : orderDetails) {
        totalPriceOrder = totalPriceOrder + orderDetail.totalPriceOrderDetail();
        }
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currency = NumberFormat.getCurrencyInstance(localeVN);
        String priceFormatted = currency.format(totalPriceOrder);
        return priceFormatted;
        
    }
    public String getTotalPriceFormatted02(){
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        String priceFormatted = currency.format(totalPrice);
        return priceFormatted;
    }
    public int compareTo(OrdersEntity order) {
            if(getOrderDate() == null || order.getOrderDate() == null)
                return 0;
            return getOrderDate().compareTo(order.getOrderDate());
	}
}

src/main/java/com/mycompany/jv30_project_final02/controller/HomeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv30_project_final02.controller;

import com.google.gson.Gson;
import com.mycompany.jv30_project_final02.common.AjaxProduct;
import com.mycompany.jv30_project_final02.service.AccountRoleService;
import com.mycompany.jv30_project_final02.entities.AccountEntity;
import com.mycompany.jv30_project_final02.entities.CustomerEntity;
import com.mycompany.jv30_project_final02.entities.FavoriteEntity;
import com.mycompany.jv30_project_final02.entities.MemoryEntity;
import com.mycompany.jv30_project_final02.entities.OrderDetailEntity;
import com.mycompany.jv30_project_final02.entities.OrdersEntity;
import com.mycompany.jv30_project_final02.entities.ProducerEntity;
import com.mycompany.jv30_project_final02.entities.ProductDetailEntity;
import com.mycompany.jv30_project_final02.entities.ProductEntity;
import com.mycompany.jv30_project_final02.entities.PromotionEntity;
import com.mycompany.jv30_project_final02.entities.ReviewEntity;
import com.mycompany.jv30_project_final02.enums.Gender;
import com.mycompany.jv30_project_final02.enums.StatusAccount;
import com.mycompany.jv30_project_final02.enums.StatusOrder;
import com.mycompany.jv30_project_final02.service.AccountService;
import com.mycompany.jv30_project_final02.service.ColorService;
import com.mycompany.jv30_project_final02.service.CustomerService;
import com.mycompany.jv30_project_final02.service.FavoriteService;
import com.mycompany.jv30_project_final02.service.ImagesService;
import com.mycompany.jv30_project_final02.service.MailService;
import com.mycompany.jv30_project_final02.service.MemoryService;
import com.mycompany.jv30_project_final02.service.OrderDetailService;
import com.mycompany.jv30_project_final02.service.ProducerService;
import com.mycompany.jv30_project_final02.service.ProductDetailService;
import com.mycompany.jv30_project_final02.service.ProductService;
import com.mycompany.jv30_project_final02.service.PromotionService;
import com.mycompany.jv30_project_final02.service.ReviewService;
import com.mycompany.jv30_project_final02.utils.HasCode;
import java.text.NumberFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 *
 * @author AnhLe
 */
@Controller
public class HomeController {

    @Autowired
    private ProductService productService;

    @Autowired
    private ProductDetailService productDetailService;

    @Autowired
    private ColorService colorService;

    @Autowired
    private MemoryService memoryService;

    @Autowired
    private MemoryService memoryService1;

    @Autowired 
    private ImagesService imageService;

    @Autowired
    private ProducerService producerService;

    @Autowired
    private CustomerService customerService;

    @Autowired
    private MailService mailService;

    @Autowired
    private PromotionService promotionService;
    
    @Autowired
    private AccountService accountService;
    
    @Autowired
    private FavoriteService favoriteService;
    
    @Autowired
    private OrderDetailService orderDetailService;
    
    @Autowired
    private AccountRoleService accountRoleService;
    
    @Autowired
    private ReviewService reviewService;
    
    @RequestMapping(value = {"/", "/home"}, method = RequestMethod.GET)
    public String viewHome(Model model) {
        List<ProductDetailEntity> productDetail = productDetailService.findProductDetailLimit();
        List<ProductEntity> product = new ArrayList<>();
        for (int i = 0; i < productDetail.size(); i++) {
            ProductEntity p = productService.findByProductDetail(productDetail.get(i));
            List<ProductDetailEntity> pd = new ArrayList<>();
            pd.add(productDetail.get(i));
            p.setProductDetail(pd);
            product.add(p);
        }
        
        for(int i =0; i<product.size(); i++){
            product.get(i).setPromotion(promotionService.findByProductIdAndDateNow(product.get(i).getId()));
            product.get(i).setReview(reviewService.findByProduct(product.get(i)));
        }
        
        // Sản phẩm hot
        List<ProductEntity> product2 = new ArrayList<>();
        List<Integer> listIdProduct = orderDetailService.findIdProduct();
        for(Integer idp: listIdProduct){
            product2.add(productService.findById(idp));
        }
        for (int i = 0; i < product2.size(); i++) {
            List<ProductDetailEntity> pd = new ArrayList<>();
            pd = productDetailService.finByProduct(product2.get(i));
            product2.get(i).setProductDetail(pd);
        }
        for(int i =0; i<product2.size(); i++){
            product2.get(i).setPromotion(promotionService.findByProductIdAndDateNow(product2.get(i).getId()));
            product2.get(i).setReview(reviewService.findByProduct(product2.get(i)));
        }
        model.addAttribute("listProduct", product);
        model.addAttribute("listProduct2", product2);
        return "home";
    }

    @RequestMapping("/login")
    public String viewLogin(Model model,
            @RequestParam(value = "isError", required = false) boolean isError) {
        if (isError) {
            model.addAttribute("message", "Đăng nhập không thành công!!.");
        }
        return "login";
    }

    @RequestMapping(value = "/product-detail/{id}", method = RequestMethod.GET)
    public String viewProductDetail(@PathVariable(value = "id", required = false) int id, Model model) {
        ProductDetailEntity productDetail = productDetailService.findById(id);
        if(productDetail !=null && productDetail.getId()>0){
            productDetail.setColor(colorService.findByProductDetail(productDetail));
            productDetail.setMemory(memoryService.findByProductDetail(productDetail));
            productDetail.getProduct().setImage(imageService.findByProduct(productDetail.getProduct()));
            Set<PromotionEntity> promotion = promotionService.findByProductIdAndDateNow(productDetail.getProduct().getId());
            model.addAttribute("promotion", promotion);
            model.addAttribute("productDetail", productDetail);
            List<MemoryEntity> listMemory = memoryService1.findByProductId(productDetail.getProduct().getId());
            for (int i = 0; i < listMemory.size(); i++) {
                listMemory.get(i).setProductDetail(productDetailService.finByMemoryAndProduct(listMemory.get(i), productDetail.getProduct()));
            }
            model.addAttribute("listMemory", listMemory);
            // sản phẩm tương tự
            List<ProductDetailEntity> listProductDetail = productDetailService.findByProducerIdLimit(producerService.findByProduct(productDetail.getProduct()).getId());
            for(int i=0; i<listProductDetail.size(); i++){
                listProductDetail.get(i).getProduct().setPromotion(promotionService.findByProductIdAndDateNow(listProductDetail.get(i).getProduct().getId()));
            }
            model.addAttribute("listProductDetail", listProductDetail);
            
            // check riview and favorite
            Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
            if (principal instanceof AccountEntity) {
                AccountEntity account = (AccountEntity)principal;
                List<OrderDetailEntity> orderDetails = orderDetailService.findByProductAndAccountAndStatusOrder(productDetail.getProduct(), account, StatusOrder.Done);
                if(orderDetails.size()>0){
                    model.addAttribute("checkComment", "checkComment");
                }
                FavoriteEntity favorite = favoriteService.findByAccountAndProduct(account, productDetail.getProduct());
                model.addAttribute("favorite", favorite);
            } 
            
            // list riview
            List<ReviewEntity> riviews = reviewService.findByProductOrderByIdDesc(productDetail.getProduct());
            model.addAttribute("riviews", riviews);
        }
        return "product-detail";
    }

    @RequestMapping("order/{productDetailId}")
    @ResponseBody
    public String order(@RequestBody @PathVariable("productDetailId") int productDetailId,
            Model model,
            HttpSession session) {
        OrdersEntity order = (OrdersEntity) session.getAttribute("order");
        if (order == null) {
            order = new OrdersEntity();
        }

        List<OrderDetailEntity> orderDetail = order.getOrderDetails();
        if (orderDetail == null) {
            orderDetail = new ArrayList<>();
        }
        ProductDetailEntity produceDetail = productDetailService.findById(productDetailId);
        produceDetail.setProduct(productService.findByProductDetail(produceDetail));
        List<ProductDetailEntity> listProductDetail1 = new ArrayList<>();
        listProductDetail1.add(produceDetail);

src/main/webapp/WEB-INF/jsp/user/change-password.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html lang="en">
<head>
  	<title>Đổi mật khẩu</title>
  	<meta charset="utf-8">
  	<jsp:include page="../include/user/css-header.jsp" />
</head>
<body>
    <jsp:include page="../include/user/header-area.jsp" />
    
    <div style="margin:10px;">
        <div class="container" >
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-12 pr-title">
                        <div class="col-sm-12 title-content" >
                            <p>Trang chủ <span class="glyphicon glyphicon-chevron-right"></span> Đổi mật khẩu</p>
                            
                        </div>
                        <div class="col-sm-12" style="margin-bottom: 20px;">
                            <div class="login">
                                <div class="account-login">
                                    <h3 style="text-align: center;color: red;">
                                        Đổi mật khẩu
                                    </h3>
                                    <form action="${pageContext.request.contextPath}/user/change-password" 
                                          class="login-form form-horizontal" method="POST"
                                          modelAttribute="account" class="form-update">
                                        <c:if test="${mess == 'incorrect'}">
                                            <p class="already_exist">
                                                <span class="glyphicon glyphicon-remove"></span>
                                                Mật khẩu cũ không đúng
                                            </p>
                                        </c:if>
                                        <c:if test="${mess == 'not_match'}">
                                            <p class="already_exist">
                                                <span class="glyphicon glyphicon-remove"></span>
                                                Mật khẩu không khớp nhau
                                            </p>
                                        </c:if>
                                        <div class="form-group">
                                            <label class="control-label col-sm-4" for="password">Mật khẩu cũ:</label>
                                            <div class="col-sm-8">
                                                <input id="password" type="password" name="oldPass" placeholder="Nhập mật khẩu cũ"  
                                                   class="form-control" required>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-sm-4" for="new-pass">Mật khẩu mới:</label>
                                            <div class="col-sm-8">
                                                <input id="new-pass" type="password" name="newPass" placeholder="Nhập mật khẩu mới"  
                                                   class="form-control" required>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-sm-4" for="again-password">Nhập lại mật khẩu:</label>
                                            <div class="col-sm-8">
                                                <input id="again-password" type="password" name="againPass" placeholder="Nhập lại mật khẩu mới"  
                                                   class="form-control" required>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-sm-4"></label>
                                            <div class="col-sm-8">
                                                <button type="submit" class="btn btn-login">Cập nhật</button>
                                            </div>
                                        </div>  
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <jsp:include page="../include/user/footer.jsp"/>
    <jsp:include page="../include/user/script-footer.jsp"/>
    <script>
        
    </script>
</body>

src/main/webapp/WEB-INF/jsp/user/home.jsp
<%-- 
    Document   : home
    Created on : Jun 20, 2019, 7:47:58 PM
    Author     : AnhLe
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>${message}</h1>
        <jsp:include page="../include/menu.jsp" />
    </body>
</html>

src/main/webapp/WEB-INF/jsp/user/list-order.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Đơn hàng của tôi</title>
    <meta charset="utf-8">
    <jsp:include page="../include/user/css-header.jsp" />
</head>
<body>
    <jsp:include page="../include/user/header-area.jsp" />

    <div style="margin:10px;">
        <div class="container" >
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-12 pr-title"> 
                        <div class="col-sm-12 title-content" >
                            <p style="margin-bottom:  40px;">Trang chủ <span class="glyphicon glyphicon-chevron-right"></span> Đơn hàng của tôi</p>
                            <div>
                                <button type="button" class="btn btn-info" 
                                    onclick="location.href = '<c:url value='/user/dowload-order' />'">Xuất file excel
                                </button>
                                <div class="div-s-or">
                                    <c:choose>
                                        <c:when test="${all == 'all'}">
                                            <c:set var="url" value="user/list-order/search-order" />
                                        </c:when>
                                        <c:otherwise>
                                            <c:set var="url" value="user/list-order/${tab}/search-order" />
                                        </c:otherwise>
                                    </c:choose>
                                    <form action="${pageContext.request.contextPath}/${url}" method="POST">
                                        <label>Từ :</label>
                                        <input id="startDate" type="date" value="${startDate}" name="startDate" required/>
                                        <label style="margin-left:10px;">Đến :</label>
                                        <input id="endDate" type="date" value="${endDate}" name="endDate" required/>
                                        <button type="submit" class="btn btn-primary search-order">Tìm kiếm</button>
                                    </form>
                                </div> 
                                <div class="div-s-tab">
                                    <c:choose>
                                        <c:when test="${all == 'all'}">
                                            <a href="<c:url value="/user/list-order" />" style="color: red;">Tất cả</a>
                                        </c:when>
                                        <c:otherwise>
                                            <a href="<c:url value="/user/list-order" />">Tất cả</a>
                                        </c:otherwise>
                                    </c:choose>
                                    <c:forEach var="s" items="${listStatus}">
                                        <c:choose>
                                            <c:when test="${s == tab}">
                                                <a href="<c:url value="/user/list-order/${s}" />" style="color: red;">${s.statusOrder}</a>
                                            </c:when>
                                            <c:otherwise>
                                                <a href="<c:url value="/user/list-order/${s}" />">${s.statusOrder}</a>
                                            </c:otherwise>
                                        </c:choose>

                                    </c:forEach>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12" style="margin-bottom: 20px;min-height: 300px;">
                            <c:choose>
                                <c:when test="${fn:length(orders) == 0}">
                                    <h4 class="text-color">Không có đơn hàng nào</h4>
                                </c:when>
                                <c:otherwise>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Mã ĐH</th>
                                                <th>Ngày đặt</th>
                                                <th>Tổng tiền</th>
                                                <th>Họ tên người nhận</th>
                                                <th>Email</th>
                                                <th>Số điện thoại</th>
                                                <th>Trạng thái</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <c:forEach var="i" begin="1" end="${fn:length(orders)}" step="1">
                                                <c:set var="j" value="${fn:length(orders)-i}" scope="page"></c:set>
                                                <tr class="tr-list-order">
                                                    <input type="hidden" class="id_order" value="${orders[j].id}" />
                                                    <td class="cur-list">
                                                        ${orders[j].id} 
                                                    </td>
                                                    <td class="cur-list">
                                                        ${orders[j].orderDateFormatted}
                                                    </td>
                                                    <td class="cur-list">${orders[j].totalPriceFormatted}</td>
                                                    <td class="cur-list">
                                                        ${orders[j].customer.name}
                                                    </td>
                                                    <td class="cur-list">
                                                        ${orders[j].customer.email}
                                                    </td>
                                                    <td class="cur-list">
                                                        ${orders[j].customer.phoneNumber}
                                                    </td>
                                                    <td class="cur-list status">
                                                        ${orders[j].status.statusOrder}
                                                    </td>
                                                    <td>
                                                        <c:if test="${orders[j].status == 'Ordered'}">
                                                            <button type="button" class="btn btn-warning cancel-od">Hủy đơn hàng</button>
                                                        </c:if>
                                                    </td>
                                                </tr>
                                            </c:forEach>
                                        </tbody>
                                    </table>
                                </c:otherwise>
                            </c:choose>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <jsp:include page="../include/user/footer.jsp"/>
    <jsp:include page="../include/user/script-footer.jsp"/>
    <script>
        $(document).ready(function () {
            $(".cur-list").click(function () {
                var id = $(this).parent().find(".id_order").val();
                location.href = '<c:url value="/user/order-detail/" />' + id;
            });

            // Hủy đơn hàng
            $(".cancel-od").click(function(){
                var id = $(this).parents("tr").find(".id_order").val();
                let $this = $(this);
                $.ajax({
                    type : "GET",
                    url: "<c:url value="/user/cancle-order/" />"+id,
                    dataType : 'json',
                    timeout : 100000,
                    success :function (data){  
                        let status = JSON.parse(data);
                        if(status.status == "ok"){
                            $this.parents("tr").find(".status").text("Đã hủy");
                            $this.remove();
                        }
                    },
                    error:function(e){
                        console.log(e);
                    }
                });
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user/message-change-pass.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html lang="en">
<head>
  	<title>Đổi mật khẩu</title>
  	<meta charset="utf-8">
  	<jsp:include page="../include/user/css-header.jsp" />
</head>
<body>
    <jsp:include page="../include/user/header-area.jsp" />
    
    <div style="margin:10px;">
        <div class="container" >
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-12 pr-title">
                        <div class="col-sm-12 title-content" >
                            <p>Trang chủ <span class="glyphicon glyphicon-chevron-right"></span> Đổi mật khẩu</p>
                            
                        </div>
                        <div class="col-sm-12" style="margin-bottom: 20px;">
                            <div class="login">
                                <div class="account-login">
                                    <p class="success-s">
                                        <span class="glyphicon glyphicon-ok"></span>
                                        Đổi mật khẩu thành công
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <jsp:include page="../include/user/footer.jsp"/>
    <jsp:include page="../include/user/script-footer.jsp"/>
    <script>
       
    </script>
</body>