src/main/java/com/mycompany/jv30_project_final02/entities/ProductDetailEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv30_project_final02.entities;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;

/**
 *
 * @author HOANGBAO
 */
@Entity
@Table(name ="product_detail")
public class ProductDetailEntity implements Serializable{
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne      
    @JoinColumn(name ="product_id")
    private ProductEntity product;
    
    @ManyToOne      
    @JoinColumn(name ="color_id")
    private ColorEntity color;
    
    @ManyToOne      
    @JoinColumn(name ="memory_id")
    private MemoryEntity memory;

    private Double price;
    
    
    private String image;
    
    @Column(name = "quantity_in_store")
    private int quantityInStore;
    
    public ProductDetailEntity() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ProductEntity getProduct() {
        return product;
    }

    public void setProduct(ProductEntity product) {
        this.product = product;
    }

    public ColorEntity getColor() {
        return color;
    }

    public void setColor(ColorEntity color) {
        this.color = color;
    }

    public MemoryEntity getMemory() {
        return memory;
    }

    public void setMemory(MemoryEntity memory) {
        this.memory = memory;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public int getQuantityInStore() {
        return quantityInStore;
    }

    public void setQuantityInStore(int quantityInStore) {
        this.quantityInStore = quantityInStore;
    }
    
    public String getPriceFormatted(){
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currency = NumberFormat.getCurrencyInstance(localeVN);
        String priceFormatted = currency.format(price);
        return priceFormatted;
    }
//    public String getPriceFormatted(){
////        Locale localeVN = new Locale("vi", "VN");
////        NumberFormat currency = NumberFormat.getCurrencyInstance(localeVN);
//        DecimalFormat formatter = new DecimalFormat("###,###,###");
//        String priceFormatted = (formatter.format(price) + " đ");
//        return priceFormatted;
//    }
     public String getDiscount(){
         double priceDiscount = price - (price * ((product.totalPromotion() * 1.0)/100));
         Locale localeVN = new Locale("vi", "VN");
          NumberFormat currency = NumberFormat.getCurrencyInstance(localeVN);
//        DecimalFormat formatter = new DecimalFormat("###,###,###");
//        String priceFormatted = (formatter.format(priceDiscount) + " đ");
          String priceFormatted = currency.format(priceDiscount);
        return priceFormatted;
    }
}

src/main/java/com/mycompany/jv30_project_final02/controller/ManagerController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv30_project_final02.controller;

import com.google.gson.Gson;
import com.mycompany.jv30_project_final02.entities.AccountEntity;
import com.mycompany.jv30_project_final02.entities.ColorEntity;
import com.mycompany.jv30_project_final02.entities.CustomerEntity;
import com.mycompany.jv30_project_final02.entities.ImageEntity;
import com.mycompany.jv30_project_final02.entities.MemoryEntity;
import com.mycompany.jv30_project_final02.entities.OrderDetailEntity;
import com.mycompany.jv30_project_final02.entities.OrdersEntity;
import com.mycompany.jv30_project_final02.entities.ProducerEntity;
import com.mycompany.jv30_project_final02.entities.ProductDetailEntity;
import com.mycompany.jv30_project_final02.entities.ProductEntity;
import com.mycompany.jv30_project_final02.entities.ReviewEntity;
import com.mycompany.jv30_project_final02.enums.Gender;
import com.mycompany.jv30_project_final02.service.AccountService;
import com.mycompany.jv30_project_final02.service.ColorService;
import com.mycompany.jv30_project_final02.service.ImagesService;
import com.mycompany.jv30_project_final02.service.MemoryService;
import com.mycompany.jv30_project_final02.service.OrderDetailService;
import com.mycompany.jv30_project_final02.service.OrderService;
import com.mycompany.jv30_project_final02.service.ProducerService;
import com.mycompany.jv30_project_final02.service.ProductDetailService;
import com.mycompany.jv30_project_final02.service.ProductService;
import com.mycompany.jv30_project_final02.service.PromotionService;
import com.mycompany.jv30_project_final02.service.ReviewService;
import com.mycompany.jv30_project_final02.utils.ExportExcel;
import com.mycompany.jv30_project_final02.utils.HasCode;
import com.mycompany.jv30_project_final02.utils.UpLoadFile;
import java.io.IOException;
import java.io.OutputStream;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.apache.poi.ss.usermodel.Workbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

/**
 *
 * @author Hi_XV
 */
@Controller
@RequestMapping("/manager")
public class ManagerController{
    @Autowired
    AccountService accountService;
    
    @Autowired
    ProductService productService;
    
    @Autowired
    ProducerService producerService;
    
    @Autowired
    ProductDetailService productDetailService;
    
    @Autowired
    ColorService colorService;
    
    @Autowired
    MemoryService memoryService;
    
    @Autowired
    ServletContext servletContext;
    
    @Autowired
    ImagesService imagesService;
    
    @Autowired
    UpLoadFile upLoadFile;
    
    @Autowired
    OrderService orderService;
    
    @Autowired
    PromotionService promotionService;
    
    @Autowired
    ReviewService reviewService;
    
    @Autowired
    OrderDetailService orderDetailService;
    
    @RequestMapping(value = {"/homeManager", "/"}, method = RequestMethod.GET)
    public String getManages(Model model){
        int sumOrder = orderService.findSumOrderDone();
        int sumReview = reviewService.findSumReview();
        int sumPromotion = promotionService.findSumPromotion();
        double sumOrderPriceDone = orderService.findPriceOrder();
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currency = NumberFormat.getCurrencyInstance(localeVN);
        String priceFormatted = currency.format(sumOrderPriceDone);
        model.addAttribute("sumOrder", sumOrder);
        model.addAttribute("sumReview", sumReview);
        model.addAttribute("sumPromotion", sumPromotion);
        model.addAttribute("sumOrderPriceDone", priceFormatted);
        
        return "manager/home-manages";
    }
     
    @RequestMapping(value = {"/viewlistProduct"}, method = RequestMethod.GET)
    public String getProduct(Model model){
        List<ProductEntity> products = productService.getProduct();
        for (ProductEntity product : products) {
            List<ProductDetailEntity> productDetails = productDetailService.getProductId(product.getId());
            List<ImageEntity> images = imagesService.getProductId(product.getId());
            product.setProductDetail(productDetails);
            product.setImage(images);
        }
        Collections.sort(products, new Comparator<ProductEntity>() {
        @Override
        public int compare(ProductEntity o1, ProductEntity o2) {
        return o2.getDateCreate().compareTo(o1.getDateCreate());
        }
        });
    model.addAttribute("products", products);
    return "manager/listProduct";
    }
    @RequestMapping("/add-product")
    public String addProduct(Model model){
        
        model.addAttribute("product", new ProductEntity());
        model.addAttribute("producers", producerService.getProducer());
        model.addAttribute("action", "add-product");
        return "manager/form-Product";
    }
    @RequestMapping(value = {"/add-product"}, method = RequestMethod.POST)
    public String saveProduct(Model model,@Valid @ModelAttribute("product") ProductEntity product, BindingResult result,
            @RequestParam("files") List<MultipartFile> files){
        if(result.hasErrors()){
            model.addAttribute("product", product);
        model.addAttribute("producers", producerService.getProducer());
        model.addAttribute("action", "add-product");
        return "manager/form-Product";
        }else{
            List<String> urls = new ArrayList<>();
        String pathName = "D:\\TrungTam\\DoAn\\DienThoai\\Java\\Mau7\\DienThoai\\src\\main\\webapp\\resources\\images\\phone";
//                   servletContext.getRealPath("/resources/upload/");
        urls = upLoadFile.upLoadImage(files, pathName);

        productService.saveProduct(product, urls);
        return "redirect:/manager/viewlistProduct";
        }
        
    }
    @RequestMapping("/edit-product/{productId}")
    public String editProduct(Model model, @PathVariable("productId") int productId){
        List<ImageEntity> images = imagesService.getProductId(productId);
        model.addAttribute("producers", producerService.getProducer());
        model.addAttribute("product", productService.findProductId(productId));
        model.addAttribute("images", images);
        model.addAttribute("action", "edit-product");
        return "manager/form-Product";
    }
    @RequestMapping(value = {"/edit-product"}, method = RequestMethod.POST)
    public String saveEditProduct(Model model, @ModelAttribute("product") ProductEntity product)
            {
        
//        List<String> urls = new ArrayList<>();
//        String pathName = 
//                   servletContext.getRealPath("/resources/upload/");
//        urls = UpLoadFile.upLoadImage(files, pathName);
        productService.saveProductId(product);
        return "redirect:/manager/viewlistProduct";
    }
    @RequestMapping(value = {"edit-images"}, method = RequestMethod.POST)
    public String editImages(Model model, @ModelAttribute("product") ProductEntity product,
              @RequestParam("files") List<MultipartFile> files){
         List<String> urls = new ArrayList<>();
        String pathName = "D:\\TrungTam\\DoAn\\DienThoai\\Java\\Mau7\\DienThoai\\src\\main\\webapp\\resources\\images\\phone";
//                   servletContext.getRealPath("/resources/upload/");
        urls = upLoadFile.upLoadImage(files, pathName);
        productService.saveImage(product, urls);
        model.addAttribute("action","edit-images");
        return "redirect:/manager/edit-product/"+product.getId();
    }
   @RequestMapping("/deleteImages/{imageId}")
      public String DeleteImages(Model model,@PathVariable("imageId") int imageId){
          ImageEntity image = imagesService.findImage(imageId);
          ProductEntity product = productService.findProductId(image.getProduct().getId());
          imagesService.deleteImage(imageId);
          return "redirect:/manager/edit-product/"+product.getId();
      }
     @RequestMapping("/update-Status/{productId}")
      public String updateStatus(Model model,
              @PathVariable("productId") int productId, @RequestParam("status") int status){
          ProductEntity product = productService.findProductId(productId);
          productService.updateStatus(product, status);
          return "redirect:/manager/viewlistProduct";
      }
    
      @RequestMapping("/addProducrDetail/{productId}") 
      public String uploadProductDetail(Model model, @PathVariable("productId") int productId){
          
          List<ProductDetailEntity> productDetails = productDetailService.getProductId(productId);
          model.addAttribute("product", productService.findProductId(productId));
          model.addAttribute("productDetails", productDetails);
          model.addAttribute("memorys", memoryService.getMemory());
          model.addAttribute("colors", colorService.getColor());

src/main/webapp/WEB-INF/jsp/manager/addProductDetail.jsp
<%-- 
    Document   : productDetail
    Created on : Dec 16, 2019, 2:32:20 PM
    Author     : Hi_XV
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="mvc" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>JSP Page</title>
        <jsp:include page="../include/manages/css-header-manages.jsp"/>

    </head>
    <body>
        <div id="wrapper">
            <jsp:include page="../include/manages/header-area-manages.jsp"/>
            <div id="page-wrapper">
                <div class="container-fluid" style="margin-top: 20px">
                    <div class="row">
                        <div class="col-sm-12 col-lg-12" style="text-align: center">
                            <h2>Thêm Bộ nhớ</h2>
                        </div>
                    </div>

                    <div class="row">
                        <mvc:form action="${pageContext.request.contextPath}/manager/${action}" method="post" 
                                  modelAttribute="product">
                            <c:if test="${action == 'addProductDetail'}">
                                <input hidden name="id" value="${product.id}" />
                            </c:if>
                            <div class="col-sm-6 col-lg-4">
                                <div class="form-group">
                                    <label for="memoryId">Bộ nhớ</label>
                                    <select name="memory" class="form-control" id="memoryId">
                                        <c:forEach items="${memorys}" var="m">
                                            <option value="${m.memory}">${m.memory}</option>
                                        </c:forEach>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-6 col-lg-4">
                                <div class="form-group">
                                    <label for="priceId">Giá</label>
                                    <input id="priceId" name="price" class="form-control" required
                                           value="" placeholder="Gía sản phẩm....."/>
                                </div>
                            </div>
                            <div class="col-sm-6 col-lg-4">
                                <div class="form-group">
                                    <label for="quantityInStoreId">Số lượng trong cửa hàng</label>
                                    <input id="quantityInStoreId" name="quantityInStore" required class="form-control" value="" placeholder="Nhập số lượng....."/>
                                </div>
                            </div>
                            <div class="col-sm-12 col-lg-12">
                                <div class="form-group">
                                    <label>
                                        Color
                                    </label>
                                    <div class="checkbox">
                                        <c:forEach items="${colors}" var="c">
                                            <label>
                                                <input type="checkbox"  name="colors" value="${c.color}" style="margin-left: -15px"/>
                                                <div class="col-sm-1" style=" width: 60px; height: 30px; box-shadow: 3px 3px #666; background:<c:out value="${c.color}"/>">
                                                </div>
                                            </label>
                                        </c:forEach>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group" style="text-align: center">
                                <button type="submit" class="btn btn-primary">Thêm</button>
                            </div>
                        </mvc:form>
                    </div> 
                    <div class="row">
                        <div class="col-sm-12 col-lg-12">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tr class="bg-success">
                                        <th scope="col">Image</th>
                                        <th scope="col">QuantityInStore</th>
                                        <th scope="col">Memory</th>
                                        <th scope="col">Color</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">&nbsp;</th>
                                    </tr>

                                    <c:forEach items="${productDetails}" var="p" >
                                        <tr>
                                            <td>
                                                <div class="col-sm-5 col-lg-5">
                                                    <image src="<c:url value="/resources/images/product_detail/${p.image}"/>" 
                                                       style="width: 120px; height: 120px"/>
                                                </div>
                                                <div class="col-sm-7 col-lg-7">
                                                    <mvc:form action="${pageContext.request.contextPath}/manager/update-ImagePd/${p.id}" method="post" 
                                                              enctype="multipart/form-data"
                                                              class="form-horizontal">
                                                        <div class="form-group">
                                                            <input name="files" type="file" class="form-control" multiple="multiple"/>
                                                        </div>
                                                        <div class="form-group" style="text-align: left">
                                                            <button type="submit" class="btn btn-success">update</button>
                                                        </div>
                                                    </mvc:form> 
                                                </div>
                                            </td>
                                            <td><c:out value="${p.quantityInStore}"/></td>
                                            <td><c:out value="${p.memory.memory}"/></td>
                                            <td><div class="col-sm-1" style=" width: 60px; height: 30px; box-shadow: 3px 3px #666; background:<c:out value="${p.color.color}"/>">
                                                </div></td>
                                            <td><c:out value="${p.getPriceFormatted()}"/></td>
                                            <td>

                                                <button class="btn btn-danger glyphicon glyphicon-trash" 
                                                        onclick="location.href = '<c:url value="/manager/deleteProductDetail/${p.id}"/>'">

                                                </button>
                                            </td>

                                        </tr>
                                    </c:forEach>   
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <jsp:include page="../include/manages/footer-manages.jsp"/>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/manager/addPromotionProduct.jsp
<%-- 
    Document   : productDetail
    Created on : Dec 16, 2019, 2:32:20 PM
    Author     : Hi_XV
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="mvc" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>JSP Page</title>
        <jsp:include page="../include/manages/css-header-manages.jsp"/>

    </head>
    <body>
        <div id="wrapper">
            <jsp:include page="../include/manages/header-area-manages.jsp"/>
            <div id="page-wrapper">
                <div class="container-fluid" style="margin-top: 20px;">
                     <div class="row">
                        <div class="col-sm-12 col-lg-12" style="text-align: center">
                            <h2>Thêm sản phẩm vào khuyến mãi</h2>
                        </div>
                    </div>
                    <div class="row">
                        <mvc:form action="${pageContext.request.contextPath}/manager/${action}" method="post" 
                                   class="form-horizontal">
                            <c:if test="${action == 'promotion-product'}">
                                <input hidden name="id" value="${promotion.id}" />

                            </c:if>

                                <div class="col-sm-12 col-lg-12" style="border-bottom: 1px solid #000">
                                <div class="form-group">
                                    <b><h3 style="color: #002a80">${promotion.name}</h3></b>
                                   <b><h4 style="color: #008000;">Thời gian khuyến mãi từ ngày ${promotion.startDate} đến ngày ${promotion.endDate}</h4></b>
                                    <b><h4 style="color: #008000">Giảm ${promotion.discount}%</h4></b>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-sm-12 col-lg-12">
                                    <h3 style="margin-left: 150px;"><b>Danh sách sản phẩm</b></h3>
                                </div>
                                    
                                
                                <div class="col-sm-12 checkbox">
                                    <c:forEach items="${products}" var="p">
                                        <div class="col-sm-3">
                                            <p style="width: 200px; background: #E6E6E6;padding: 5px; margin-top: 5px; box-shadow: 1px 1px 3px 1px  #2E2E2E;"><label class="container"><input type="checkbox" name="ListProductId" value="${p.id}"/><b>${p.name}</b></p><span class="checkmark"></span></label>
                                        </div>
                                           
                                        
                                    </c:forEach>

                                </div>
                                </div>
                            
                            <div class="form-group" style="text-align: center">
                                <button type="submit" class="btn btn-primary">Thêm sản phẩm</button>
                            </div>
                        </mvc:form>
                    </div> 
                  
                </div>

            </div>
        </div>
        <jsp:include page="../include/manages/footer-manages.jsp"/>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/manager/form-Memory.jsp
<%-- 
    Document   : form-Memory
    Created on : Dec 19, 2019, 10:40:07 AM
    Author     : Hi_XV
--%>

<%@taglib  uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib prefix="mvc" uri="http://www.springframework.org/tags/form" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../include/manages/css-header-manages.jsp"/>
    </head>
    <body>
        <div id="wrapper">
             
            <jsp:include page="../include/manages/header-area-manages.jsp"/>
            
            <div id="page-wrapper">
                <div class="container-fluid" style="margin-top: 20px;">
                    <h2>Bộ nhớ trong</h2>
            <div class="row">
                <mvc:form action="${pageContext.request.contextPath}/manager/save-Memory" method="post" 
                          enctype="multipart/form-data"
                          modelAttribute="memory" class="form-horizontal">
                    <div class="form-group">
                        <label for="nameId" class="control-label col-sm-2">
                            Bộ nhớ trong 
                        </label>
                        <div class="col-sm-3">
                            <input id="nameId" name="memory" class="form-control" value=""/>

                        </div>
                    
                        <button type="submit" class="btn btn-primary">Thêm bộ nhớ</button>
                    </div>
                </mvc:form>
            </div>
                    <div class="row">
                        <h4>Bộ nhớ trong hiện có</h4>
                        <c:forEach items="${memorys}" var="m">
                            <span class="color-memory"><c:out value="${m.memory}"/></span>
                        </c:forEach>
                    </div>
        </div>
                </div>
            </div>
        <jsp:include page="../include/manages/footer-manages.jsp"/>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/manager/listPromotion.jsp
<%-- 
    Document   : listPromotion
    Created on : Dec 17, 2019, 3:13:23 PM
    Author     : Hi_XV
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="mvc" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../include/manages/css-header-manages.jsp"/>
    </head>
    <body>
        <div id="wrapper">
            <jsp:include page="../include/manages/header-area-manages.jsp"/>
            <div id="page-wrapper">
                <div class="container-fluid" style="margin-top: 20px;">
            <h1>Khuyến mãi!</h1>
            <div class="row">
                <div class="table-responsive">
                            <table class="table table-bordered">
                    <tr class="bg-success">
                        
                        <th scope="col">Tên khuyến mãi</th>
                        
                        
                        <th scope="col">Ngày bắt đầu</th>
                        <th scope="col">Ngày kết thúc</th>
                        <th scope="col">Giảm giá</th>
                        
                       
                        <th scope="col">Action</th>

                    </tr>
               
                <c:forEach items="${promotions}" var="p" >
                    <tr>
                    
                        <td><c:out value="${p.name}"/></td>
                        
                        
                        <td><fmt:formatDate pattern = "dd-MM-yyyy" 
                                                        value='${p.startDate}'/></td>
                        <td><fmt:formatDate pattern = "dd-MM-yyyy" 
                                                        value='${p.endDate}'/></td>
                        <td><c:out value="${p.discount}"/> %</td>
                        <td>
   
                        <button class="btn btn-success glyphicon glyphicon-wrench" 
                           onclick="location.href = '<c:url value="/manager/edit-promotion/${p.id}"/>'">
                       
                   </button>
                     <button class="btn btn-primary" 
                           onclick="location.href = '<c:url value="/manager/promotion-product/${p.id}"/>'">
                       Thêm Sản phẩm khuyến mãi
                   </button> 
                        <button class="btn btn-warning" 
                           onclick="location.href = '<c:url value="/manager/listpromotion-product/${p.id}"/>'">
                       sản phẩm
                   </button>
                            </td>
                           
                            </tr>
                </c:forEach>   
                   </table>  
                </div>
            </div>
            </div>
        </div>
         <jsp:include page="../include/manages/footer-manages.jsp"/>
    </body>
</html>